//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eldevin
{
    using System;
    using System.Collections.Generic;
    
    public partial class crafting
    {
        public string item_id { get; set; }
        public string req_item { get; set; }
        public Nullable<int> req_quantity { get; set; }
        public string skill_id { get; set; }
    
        public virtual item item { get; set; }
        public virtual item item1 { get; set; }
        public virtual skill skill { get; set; }
    }
}
