//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eldevin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EldevinEntities : DbContext
    {
        public EldevinEntities()
            : base("name=EldevinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<quest> quests { get; set; }
        public virtual DbSet<quest_req> quest_req { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<crafting> craftings { get; set; }
    
        [DbFunction("EldevinEntities", "f_getTotalQtyByQuestID")]
        public virtual IQueryable<f_getTotalQtyByQuestID_Result2> f_getTotalQtyByQuestID(string qid)
        {
            var qidParameter = qid != null ?
                new ObjectParameter("qid", qid) :
                new ObjectParameter("qid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_getTotalQtyByQuestID_Result2>("[EldevinEntities].[f_getTotalQtyByQuestID](@qid)", qidParameter);
        }
    }
}
