//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eldevin
{
    using System;
    
    public partial class f_getTotalQtyByQuestID_Result2
    {
        public string item { get; set; }
        public Nullable<int> total_quantity { get; set; }
        public string skill_id { get; set; }
    }
}
