//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eldevin
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quest()
        {
            this.quest_req = new HashSet<quest_req>();
        }
    
        public string quest_id { get; set; }
        public string quest_name { get; set; }
        public string skill_id { get; set; }
    
        public virtual skill skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quest_req> quest_req { get; set; }
    }
}
