//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eldevin
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_req
    {
        public string quest_id { get; set; }
        public string item_id { get; set; }
        public Nullable<int> quest_quantity { get; set; }
    
        public virtual item item { get; set; }
        public virtual quest quest { get; set; }
    }
}
